name: sla_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.21
  - numpy=1.26.4
  - pandas=2.2.3
  - seaborn=0.13.2
  - matplotlib=3.9.2
  - scipy=1.13.1
  - statsmodels=0.14.4
  - pip:
      - prettytable==3.16.0